### ISSUE TITLE
Wiring 

### ISSUE THREAD

**Issue by erasor2010** [faeibson/ESPPWMFanControl#1]
Hi,

is there a wiring diagramm?

**Comment by faeibson** [comment]
Hi,
sorry for the late reply. I will upload the default wiring soon. Probably later this day.

**Comment by faeibson** [comment]
Hi,
please see the newly uploaded schematic folder. Hope Fritzing is sufficient for your needs? Don't know why the exported images are so crooked but well.. Tell me if you need it done in KiCad.

Regards
Fabian
